kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - mvn compile package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cp target/*.jar /data/maven/build
      - cp Dockerfile /data/maven/cache/Dockerfile
