apiVersion: apps/v1
kind: Deployment
metadata:
  name: cute-server-deployment
spec:
  selector:
    matchLabels:
      app: cute-server
  replicas: 2
  template:
    metadata:
      labels:
        app: cute-server
        version: v1.1
    spec:
      containers:
        - name: cute-server
          image: myz/cute-server:1.0
          ports:
            - containerPort: 9091
              name: cute-server
